name: Exemplo Input
run-name: Exemplo workflow para input. Executado por ${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            versao:
                type: string
                required: true
                default: "dev"
                description: "Versão da nova release"
            numero_card:
                type: number
                required: true
                description: "Numero do card da task"
            fazer_deploy:
                type: boolean
                required: true
                description: "Especifica se deve fazer deploy"
            ambiente:
                type: choice
                required: true
                description: "Ambiente de deploy"
                options:
                    - dev
                    - hmg
                    - prd                
jobs:
    valores_input:
        runs-on: ubuntu-latest
        steps:
            - name: Exbindo o contexto de input completo
              run: echo "${{ toJson(inputs) }}"
            - name: Exibindo os valores individualmente
              run: |
                echo "Esses são os valores passados no inputs"
                echo "A versão é: ${{ inputs.versao}}"
                echo "O card é: ${{ inputs.numero_card }}"
                echo "Deve fazer deplo: ${{ inputs.fazer_deploy }}"
                echo "O ambiente é: ${{ inputs.ambiente }}" 